# Generated by Django 5.2.6 on 2025-09-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Electric dreams', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('phone', models.CharField(default='+911234567890', max_length=20)),
                ('email', models.EmailField(default='support@electricdreams.com', max_length=254)),
                ('address', models.CharField(default='Chennai, India', max_length=255)),
            ],
        ),
    ]
