# Generated by Django 5.2.6 on 2025-09-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutsection_commitmentsection_servicesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='certifications',
            field=models.TextField(blank=True, help_text='Enter one certification/license per line'),
        ),
    ]
