# Generated by Django 5.2.6 on 2025-09-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactThankYou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='Thanks for reaching out. We will get back to you soon!')),
            ],
        ),
    ]
