# Generated by Django 5.2.6 on 2025-10-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_callbackrequest_emergencyelectricianpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyelectricianpage',
            name='workmanship_image',
            field=models.ImageField(blank=True, null=True, upload_to='emergency/'),
        ),
    ]
