# Generated by Django 5.2.6 on 2025-10-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_emergencyelectricianpage_workmanship_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='why_choose_us/')),
            ],
        ),
    ]
