# Generated by Django 5.2.6 on 2025-10-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_whychooseimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('electricians_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('default_profile_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
            ],
        ),
    ]
