# Generated by Django 5.2.6 on 2025-10-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='num_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Number of reviews submitted'),
        ),
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (1.0 to 5.0)', max_digits=3),
        ),
    ]
