# Generated by Django 5.2.6 on 2025-10-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_processstep_technicianhighlight_techniciansection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniciansection',
            name='highlights',
        ),
    ]
