# Generated by Django 5.2.6 on 2025-10-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_techniciansection_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Mark this as the default category'),
        ),
    ]
